name: Applicant Tracker App Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run app test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm start
